stages:
  - build
  - deploy

variables:
  NODE_ENV: production

build:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - backend/wwwroot/

deploy:
  stage: deploy
  script:
    - echo "Scalingo pull-only: rien à faire ici"
  only:
    - develop
