stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - echo "Running linting..."
    - dotnet format --verify-no-changes
  only:
    - branches  

build:
  stage: build
  script:
    - echo "Building the project..."
    - dotnet build --configuration Release
  needs:
    - lint 
  only:
    - branches  

test:
  stage: test
  script:
    - echo "Running tests..."
    - dotnet test --logger trx --results-directory TestResults
  needs:
    - build 
    
  only:
    - main  
    - merge_requests

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_MERGE_REQUEST_ID
      when: always
