name: Deploy to Scalingo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Scalingo Deployment
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "https://api.osc-fr1.scalingo.com/v1/apps/dossierschwach/deployments"
